//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvalikAshmarin.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdOrder { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
